/**
 * report-generator service
 * Handles PDF and CSV report generation
 */

import PDFDocument from 'pdfkit';
import { Parser } from '@json2csv/plainjs';
import { ChartJSNodeCanvas } from 'chartjs-node-canvas';

/**
 * Render a Chart.js config to PNG buffer using ChartJSNodeCanvas
 * @param config - Chart.js configuration object
 * @returns Promise<Buffer> - PNG image buffer
 */
async function renderChartPng(config: any): Promise<Buffer> {
    try {
        const chartJSNodeCanvas = new ChartJSNodeCanvas({
            width: 900,
            height: 320,
            backgroundColour: 'white'
        });

        const image = await chartJSNodeCanvas.renderToBuffer(config);
        return image;
    } catch (error) {
        throw new Error(`Chart rendering failed: ${(error as Error).message}`);
    }
}

export default () => ({
    /**
     * Generate a PDF report
     */
    async generatePDF(data: any) {
        return new Promise(async (resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                const buffers: Buffer[] = [];

                doc.on('data', (chunk: Buffer) => buffers.push(chunk));
                doc.on('end', () => resolve(Buffer.concat(buffers)));
                doc.on('error', reject);

                // Header section
                doc.fontSize(20).font('Helvetica-Bold').text(data.title || 'Performance Report', { align: 'center' });
                doc.moveDown(0.5);
                doc.fontSize(12).font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
                doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                doc.moveDown();

                // Report metadata
                if (data.type === 'Branch') {
                    doc.fontSize(14).font('Helvetica-Bold').text(`Branch: ${data.branch}`, { underline: true });
                    doc.moveDown(0.5);
                } else if (data.type === 'Employee') {
                    // Employee report header with summary
                    const employeeCount = data.employees?.length || 0;
                    doc.fontSize(14).font('Helvetica-Bold').text(`Employee Performance Report`, { underline: true });
                    doc.moveDown(0.3);
                    doc.fontSize(11).font('Helvetica').text(`Total Employees: ${employeeCount}`);
                    doc.moveDown(0.5);
                }

                // Date range
                doc.fontSize(11).font('Helvetica').text(`Period: ${data.dateRange}`);
                doc.fontSize(11).text(`Generated by: ${data.generatedBy}`);
                doc.moveDown(1.5);

                // KPIs/Metrics section - different layouts for Branch vs Employee
                if (data.type === 'Branch') {
                    doc.fontSize(14).font('Helvetica-Bold').text('Key Performance Indicators', { underline: true, align: 'left' });
                    doc.moveDown(0.5);

                    const items = data.kpis || data.metrics || [];
                    items.forEach((item: any) => {
                        const unitDisplay = item.unit ?? '';
                        const text = `• ${item.name}: ${item.value}${unitDisplay}`;
                        doc.fontSize(11).font('Helvetica').text(text, { indent: 20 });
                        doc.moveDown(0.4);
                    });
                } else if (data.type === 'Employee') {
                    // Professional table layout for Employee reports
                    doc.fontSize(14).font('Helvetica-Bold').text('Employee Metrics', { underline: true, align: 'left' });
                    doc.moveDown(0.8);

                    const items = data.kpis || data.metrics || [];
                    
                    // Table configuration
                    const tableTop = doc.y;
                    const tableLeft = 50;
                    const colWidths = [150, 150, 100, 80]; // Employee, Metric, Value, Unit
                    const rowHeight = 25;
                    const headerHeight = 30;

                    // Draw table header background
                    doc.rect(tableLeft, tableTop, colWidths.reduce((a, b) => a + b, 0), headerHeight)
                       .fill('#f3f4f6');

                    // Table headers
                    doc.fillColor('#1f2937')
                       .fontSize(10)
                       .font('Helvetica-Bold');
                    
                    let xPos = tableLeft + 8;
                    doc.text('Employee Name', xPos, tableTop + 9, { width: colWidths[0] - 16 });
                    xPos += colWidths[0];
                    doc.text('Metric', xPos, tableTop + 9, { width: colWidths[1] - 16 });
                    xPos += colWidths[1];
                    doc.text('Value', xPos, tableTop + 9, { width: colWidths[2] - 16 });
                    xPos += colWidths[2];
                    doc.text('Unit', xPos, tableTop + 9, { width: colWidths[3] - 16 });

                    // Draw header border
                    doc.strokeColor('#d1d5db')
                       .lineWidth(1)
                       .rect(tableLeft, tableTop, colWidths.reduce((a, b) => a + b, 0), headerHeight)
                       .stroke();

                    // Table rows
                    let currentY = tableTop + headerHeight;
                    doc.font('Helvetica').fontSize(9).fillColor('#374151');

                    items.forEach((item: any, index: number) => {
                        // Check if we need a new page
                        if (currentY > 700) {
                            doc.addPage();
                            currentY = 50;
                        }

                        // Alternate row background
                        if (index % 2 === 0) {
                            doc.rect(tableLeft, currentY, colWidths.reduce((a, b) => a + b, 0), rowHeight)
                               .fill('#f9fafb');
                            doc.fillColor('#374151');
                        }

                        // Draw cell content
                        xPos = tableLeft + 8;
                        doc.text(item.employeeName || '', xPos, currentY + 8, { width: colWidths[0] - 16, ellipsis: true });
                        xPos += colWidths[0];
                        doc.text(item.name || '', xPos, currentY + 8, { width: colWidths[1] - 16, ellipsis: true });
                        xPos += colWidths[1];
                        doc.text(String(item.value ?? ''), xPos, currentY + 8, { width: colWidths[2] - 16 });
                        xPos += colWidths[2];
                        doc.text(item.unit || '', xPos, currentY + 8, { width: colWidths[3] - 16 });

                        // Draw row border
                        doc.strokeColor('#e5e7eb')
                           .lineWidth(0.5)
                           .moveTo(tableLeft, currentY + rowHeight)
                           .lineTo(tableLeft + colWidths.reduce((a, b) => a + b, 0), currentY + rowHeight)
                           .stroke();

                        currentY += rowHeight;
                    });

                    // Draw table outer border
                    const tableHeight = headerHeight + (items.length * rowHeight);
                    doc.strokeColor('#d1d5db')
                       .lineWidth(1)
                       .rect(tableLeft, tableTop, colWidths.reduce((a, b) => a + b, 0), Math.min(tableHeight, currentY - tableTop))
                       .stroke();

                    // Draw vertical lines for columns
                    let colX = tableLeft;
                    colWidths.forEach((width, idx) => {
                        if (idx > 0) {
                            doc.moveTo(colX, tableTop)
                               .lineTo(colX, tableTop + Math.min(tableHeight, currentY - tableTop))
                               .stroke();
                        }
                        colX += width;
                    });

                    doc.y = currentY + 10;

                    // Employee Charts section - support both pre-rendered buffers and chartData for history
                    if (data.charts && Array.isArray(data.charts) && data.charts.length > 0) {
                        // Pre-rendered chart buffers from controller
                        doc.moveDown(1);
                        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                        doc.moveDown(0.5);
                        doc.fontSize(14).font('Helvetica-Bold').fillColor('#1f2937').text('Performance Comparison', { width: 500, underline: true, align: 'left' });
                        doc.moveDown(0.5);

                        for (const chartBuffer of data.charts) {
                            try {
                                if (doc.y > 400) {
                                    doc.addPage();
                                }
                                doc.image(chartBuffer, {
                                    fit: [500, 250],
                                    align: 'center'
                                });
                                doc.moveDown(0.5);
                            } catch (chartErr) {
                                strapi.log.warn(`[PDF] Failed to embed employee chart: ${(chartErr as Error).message}`);
                            }
                        }
                    } else if (data.chartData && data.chartData.labels && data.chartData.datasets) {
                        // Re-render chart from stored chartData (history downloads)
                        try {
                            doc.moveDown(1);
                            doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                            doc.moveDown(0.5);
                            doc.fontSize(14).font('Helvetica-Bold').fillColor('#1f2937').text('Performance Comparison', { width: 500, underline: true, align: 'left' });
                            doc.moveDown(0.5);

                            if (doc.y > 400) {
                                doc.addPage();
                            }

                            const chartConfig = {
                                type: 'bar' as const,
                                data: {
                                    labels: data.chartData.labels,
                                    datasets: data.chartData.datasets.map((ds: any) => ({
                                        label: ds.label || 'Performance',
                                        data: ds.data,
                                        backgroundColor: [
                                            'rgba(99, 102, 241, 0.7)',
                                            'rgba(168, 85, 247, 0.7)',
                                            'rgba(236, 72, 153, 0.7)',
                                            'rgba(34, 197, 94, 0.7)',
                                            'rgba(234, 179, 8, 0.7)',
                                            'rgba(249, 115, 22, 0.7)',
                                            'rgba(14, 165, 233, 0.7)',
                                            'rgba(20, 184, 166, 0.7)'
                                        ],
                                        borderColor: [
                                            'rgba(99, 102, 241, 1)',
                                            'rgba(168, 85, 247, 1)',
                                            'rgba(236, 72, 153, 1)',
                                            'rgba(34, 197, 94, 1)',
                                            'rgba(234, 179, 8, 1)',
                                            'rgba(249, 115, 22, 1)',
                                            'rgba(14, 165, 233, 1)',
                                            'rgba(20, 184, 166, 1)'
                                        ],
                                        borderWidth: 1
                                    }))
                                },
                                options: {
                                    responsive: false,
                                    plugins: {
                                        legend: { display: true, position: 'top' as const },
                                        title: { display: true, text: 'Performance Comparison', font: { size: 14 } }
                                    },
                                    scales: {
                                        y: { beginAtZero: true },
                                        x: { title: { display: true, text: 'Employees' } }
                                    }
                                }
                            };

                            const chartBuffer = await renderChartPng(chartConfig);
                            doc.image(chartBuffer, {
                                fit: [500, 250],
                                align: 'center'
                            });
                            doc.moveDown(0.5);
                        } catch (chartErr) {
                            strapi.log.warn(`[PDF] Failed to render chart from chartData: ${(chartErr as Error).message}`);
                        }
                    }
                }

                // Trends section with charts (Branch reports only)
                if (data.type === 'Branch' && data.series?.dates?.length >= 2) {
                    doc.moveDown(1.5);
                    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                    doc.moveDown();
                    doc.fontSize(16).font('Helvetica-Bold').text('Trends', { underline: true, align: 'left' });
                    doc.moveDown(0.5);

                    // Generate and embed charts
                    const { series } = data;

                    // Chart 1: Revenue Over Time
                    try {
                        if (doc.y > 400) {
                            doc.addPage();
                        }

                        const revenueChartConfig = {
                            type: 'line',
                            data: {
                                labels: series.dates,
                                datasets: [
                                    {
                                        label: 'Revenue',
                                        data: series.revenue,
                                        borderColor: 'rgb(75, 192, 192)',
                                        backgroundColor: 'rgba(75, 192, 192, 0.1)',
                                        borderWidth: 2,
                                        fill: true,
                                        tension: 0.3
                                    }
                                ]
                            },
                            options: {
                                responsive: false,
                                plugins: {
                                    legend: { display: true, position: 'top' },
                                    title: { display: false }
                                },
                                scales: {
                                    y: { beginAtZero: true, title: { display: true, text: 'Revenue ($)' } }
                                }
                            }
                        };

                        const revenueBuffer = await renderChartPng(revenueChartConfig);
                        doc.fontSize(12).font('Helvetica-Bold').text('Revenue Over Time');
                        doc.image(revenueBuffer, {
                            fit: [520, 220],
                            align: 'center'
                        });
                        doc.moveDown(0.5);
                    } catch (chartError) {
                        strapi.log.warn(`[PDF Chart] Revenue chart failed: ${(chartError as Error).message}`);
                    }

                    // Chart 2: Productivity Score Over Time
                    try {
                        if (doc.y > 400) {
                            doc.addPage();
                        }

                        const productivityChartConfig = {
                            type: 'line',
                            data: {
                                labels: series.dates,
                                datasets: [
                                    {
                                        label: 'Productivity Score',
                                        data: series.productivityScore,
                                        borderColor: 'rgb(153, 102, 255)',
                                        backgroundColor: 'rgba(153, 102, 255, 0.1)',
                                        borderWidth: 2,
                                        fill: true,
                                        tension: 0.3
                                    }
                                ]
                            },
                            options: {
                                responsive: false,
                                plugins: {
                                    legend: { display: true, position: 'top' },
                                    title: { display: false }
                                },
                                scales: {
                                    y: { beginAtZero: true, max: 100, title: { display: true, text: 'Score' } }
                                }
                            }
                        };

                        const productivityBuffer = await renderChartPng(productivityChartConfig);
                        doc.fontSize(12).font('Helvetica-Bold').text('Productivity Score Over Time');
                        doc.image(productivityBuffer, {
                            fit: [520, 220],
                            align: 'center'
                        });
                        doc.moveDown(0.5);
                    } catch (chartError) {
                        strapi.log.warn(`[PDF Chart] Productivity chart failed: ${(chartError as Error).message}`);
                    }

                    // Chart 3: Joined vs Left Over Time
                    try {
                        if (doc.y > 400) {
                            doc.addPage();
                        }

                        const movementChartConfig = {
                            type: 'bar',
                            data: {
                                labels: series.dates,
                                datasets: [
                                    {
                                        label: 'Joined',
                                        data: series.joinedCount,
                                        backgroundColor: 'rgba(75, 192, 75, 0.7)',
                                        borderColor: 'rgb(75, 192, 75)',
                                        borderWidth: 1
                                    },
                                    {
                                        label: 'Left',
                                        data: series.leftCount,
                                        backgroundColor: 'rgba(255, 99, 132, 0.7)',
                                        borderColor: 'rgb(255, 99, 132)',
                                        borderWidth: 1
                                    }
                                ]
                            },
                            options: {
                                responsive: false,
                                plugins: {
                                    legend: { display: true, position: 'top' },
                                    title: { display: false }
                                },
                                scales: {
                                    y: { beginAtZero: true, title: { display: true, text: 'Count' } }
                                }
                            }
                        };

                        const movementBuffer = await renderChartPng(movementChartConfig);
                        doc.fontSize(12).font('Helvetica-Bold').text('Employee Movement (Joined vs Left)');
                        doc.image(movementBuffer, {
                            fit: [520, 220],
                            align: 'center'
                        });
                        doc.moveDown(0.5);
                    } catch (chartError) {
                        strapi.log.warn(`[PDF Chart] Movement chart failed: ${(chartError as Error).message}`);
                    }
                } else if (data.type === 'Branch' && (!data.series?.dates || data.series.dates.length < 2)) {
                    doc.moveDown(1);
                    doc.fontSize(12).font('Helvetica-Oblique').text('No KPI trend data available for the selected date range.');
                    doc.moveDown(0.5);
                }

                // Footer
                doc.moveDown(1);
                doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                doc.fontSize(9).font('Helvetica').text('Generated by NabdTwin Platform', { align: 'center' });

                doc.end();
            } catch (error) {
                reject(error);
            }
        });
    },

    /**
     * Generate a CSV report
     */
    async generateCSV(data: any) {
        try {
            let csvData: any[] = [];

            if (data.type === 'Branch') {
                // Use metrics (new format from controller) with fallback to kpis (legacy)
                const items = data.metrics || data.kpis || [];

                csvData = items.map((item: any) => ({
                    'Metric': item.name ?? '',
                    'Value': item.value ?? '',
                    'Unit': item.unit ?? '',
                    'Branch': data.branch ?? '',
                    'Period': data.dateRange ?? '',
                    'GeneratedBy': data.generatedBy ?? '',
                    'GeneratedDate': data.generatedDate ?? ''
                }));

                // Log for debugging
                if (items.length === 0) {
                    strapi.log.warn('[CSV Generation] No metrics provided for Branch CSV, generating headers-only CSV');
                }
            } else if (data.type === 'Employee') {
                // Controller sends flat metrics array: { metrics: [{ employeeName, name, value, unit }, ...] }
                const items = data.metrics || [];
                
                strapi.log.info(`[CSV Generation] Processing ${items.length} employee metrics`);
                
                items.forEach((metric: any) => {
                    csvData.push({
                        'Employee': metric.employeeName ?? '',
                        'Metric': metric.name ?? '',
                        'Value': metric.value ?? '',
                        'Unit': metric.unit ?? '',
                        'Period': data.dateRange ?? '',
                        'Generated Date': data.generatedDate ?? new Date().toLocaleDateString()
                    });
                });
            }

            // Safety check: Prevent json2csv crash on empty data
            if (csvData.length === 0) {
                strapi.log.warn('[CSV Generation] No data to export, adding placeholder row');
                csvData.push({
                    'Status': 'No Data Available',
                    'Message': 'No metrics found for the selected criteria',
                    'Generated Date': new Date().toLocaleDateString()
                });
            }

            const parser = new Parser();
            const csv = parser.parse(csvData);
            return Buffer.from(csv);
        } catch (error) {
            strapi.log.error('[CSV Generation] Error:', (error as Error).message);
            throw new Error(`CSV generation failed: ${(error as Error).message}`);
        }
    }
});
